### PR TITLE
Gallery

### PR DESCRIPTION
**Pull request by forrester-aidan**
feat: added basic gallery page components, 
BREAKING CHANGE: modified routeTree.gen.ts to include '/gallery' as a viable route, modified Navbar.tsx to change route '/events/gallery' to just '/gallery', 

added icons link to index.html
fix: prettier on routeTree.gen.ts

### CODE REVIEW

**Comment by ufsasewebmaster** [comment]
Could you try pulling from sprint-2 to avoid some breaking changes

**Comment by TheRickyZhang** [comment]
A just fixed some merge conflicts with sprint-2, BUT it might have caused some code to be lost. Could you just review and make sure all your hcnages are still there? (Also make sure to write closes #{issue})

**Review by ufsasewebmaster — COMMENTED** [review]
Why is there an index.html?

**Review by ufsasewebmaster — CHANGES_REQUESTED** [review]
See above

**Comment by ufsasewebmaster** [comment]
Ik you have OS (gl) but please make sure to see my comment and fix to merge into the branch

**Comment by forrester-aidan** [comment]
I pulled from sprint-2, updated with my current gallery component and fixed the fonts, and then pushed to this branch. Is there anything I am missing? Sorry this was so late I was working on OS until 11 last night

**Pull request merged**
