### PR TITLE
Gallery

### PR DESCRIPTION
**Pull request by forrester-aidan**

### CODE REVIEW

**Comment by forrester-aidan** [comment]
I know I am supposed to handle my own merge conflict, but I'm having an issue with the about and sponsors page when merging because the file names were changed, but the merge editor is saying the file have been deleted and won't replace them. Is there any way I can get help on this?

**Comment by ufsasewebmaster** [comment]
Should be a simple fix: hard reset to sprint-3 and apply your changes again (looks like mainly one file). Then if you run pnpm lint/fix there shouldn't be any conflicts

**Comment by ufsasewebmaster** [comment]
Any update on this? I recommend creating a new branch from sprint-3 and applying the changes manually to resolve.

**Comment by ufsasewebmaster** [comment]
I'm not merging this - apply the changes to a new branch from sprint-3 to ensure no conflicts/inadvertant changes

**Pull request closed without merging**
